---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: microk8s-azure-kv-sync
  namespace: azure-kv-sync
spec:
  parameters:
    keyvaultName: <az key vault name>
    objects: |
      array:
        - |
          objectName: sample-secret
          objectType: secret
    tenantId: <tenant id>
    usePodIdentity: "false"
  provider: azure
  secretObjects:
    - secretName: csi-sample-secret
      type: Opaque
      data:
        - objectName: sample-secret
          key: sample-secret
      labels:
        reloader: enabled
