apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-kv-store
  namespace: azure-kv-sync
spec:
  provider:
    azurekv:
      tenantId: <tenant id>
      vaultUrl: https://<az key vault name>.vault.azure.net
      authSecretRef:
        clientId:
          name: secrets-store-creds
          key: clientid
        clientSecret:
          name: secrets-store-creds
          key: clientsecret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-sample-secret
  namespace: azure-kv-sync
  labels:
    reloader: enabled
spec:
  refreshInterval: 5s
  secretStoreRef:
    kind: SecretStore
    name: azure-kv-store
  data:
    - secretKey: sample-secret
      remoteRef:
        key: sample-secret

